/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as HomeLayoutImport } from './routes/_HomeLayout'
import { Route as HomeLayoutIndexImport } from './routes/_HomeLayout/index'

// Create/Update Routes

const HomeLayoutRoute = HomeLayoutImport.update({
  id: '/_HomeLayout',
  getParentRoute: () => rootRoute,
} as any)

const HomeLayoutIndexRoute = HomeLayoutIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomeLayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_HomeLayout': {
      id: '/_HomeLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof HomeLayoutImport
      parentRoute: typeof rootRoute
    }
    '/_HomeLayout/': {
      id: '/_HomeLayout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof HomeLayoutIndexImport
      parentRoute: typeof HomeLayoutImport
    }
  }
}

// Create and export the route tree

interface HomeLayoutRouteChildren {
  HomeLayoutIndexRoute: typeof HomeLayoutIndexRoute
}

const HomeLayoutRouteChildren: HomeLayoutRouteChildren = {
  HomeLayoutIndexRoute: HomeLayoutIndexRoute,
}

const HomeLayoutRouteWithChildren = HomeLayoutRoute._addFileChildren(
  HomeLayoutRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof HomeLayoutRouteWithChildren
  '/': typeof HomeLayoutIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof HomeLayoutIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_HomeLayout': typeof HomeLayoutRouteWithChildren
  '/_HomeLayout/': typeof HomeLayoutIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/'
  id: '__root__' | '/_HomeLayout' | '/_HomeLayout/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  HomeLayoutRoute: typeof HomeLayoutRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  HomeLayoutRoute: HomeLayoutRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_HomeLayout"
      ]
    },
    "/_HomeLayout": {
      "filePath": "_HomeLayout.tsx",
      "children": [
        "/_HomeLayout/"
      ]
    },
    "/_HomeLayout/": {
      "filePath": "_HomeLayout/index.tsx",
      "parent": "/_HomeLayout"
    }
  }
}
ROUTE_MANIFEST_END */
